version: '3.5'

services:
  postgres:
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=aboba
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:14.10-alpine